# Generated by Django 4.0.4 on 2022-07-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instagram',
        ),
    ]
