# Generated by Django 4.0.6 on 2022-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datastore_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='data',
            field=models.ManyToManyField(blank=True, to='api.data'),
        ),
    ]
