# Generated by Django 4.0.6 on 2022-08-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_datastore_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
