# Generated by Django 4.1.5 on 2023-02-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YT_Video',
            new_name='Videos',
        ),
    ]
