# Generated by Django 4.1.5 on 2023-02-23 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_devices"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Devices",
            new_name="Device",
        ),
    ]
