# Generated by Django 4.1.5 on 2023-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_videos_user_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='video',
        ),
        migrations.AddField(
            model_name='user',
            name='videos',
            field=models.ManyToManyField(to='base.yt_video'),
        ),
        migrations.AlterField(
            model_name='yt_video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
