# -*- coding: utf-8 -*-
"""NLP SEA1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jtNpIAULr_VpAEM4x3fxeoxHDoyXPo8z

1. Tokenization and Sentence Segmentation
"""

import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

nltk.download("punkt_tab")

text = "Artificial intelligence is useful. It helps students learn."

sentences = sent_tokenize(text)
words = word_tokenize(text)

print("Sentences:")
print(sentences)

print("Words:")
print(words)

print("Number of sentences:", len(sentences))
print("Number of words:", len(words))

"""2. Stop Word Removal, Stemming and Lemmatization"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

text = "The children are playing games happily."

words = word_tokenize(text)

stop_words = set(stopwords.words("english"))

filtered = [w for w in words if w.lower() not in stop_words]

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

print("After stopword removal:")
print(filtered)

print("Stemming:")
for word in filtered:
    print(word, "->", stemmer.stem(word))

print("Lemmatization:")
for word in filtered:
    print(word, "->", lemmatizer.lemmatize(word))

"""3. Regular Expression Extraction"""

import re

text = """
Contact abc@gmail.com or call +91-9876543210.
Visit https://example.com on 18-09-2026.
Follow #NLP2026.
"""

emails = re.findall(r"[\w.-]+@[\w.-]+\.\w+", text)
phones = re.findall(r"\+91[-\s]?\d{10}", text)
dates = re.findall(r"\d{2}[-/]\d{2}[-/]\d{4}", text)
urls = re.findall(r"https?://\S+", text)
hashtags = re.findall(r"#\w+", text)

print("Emails:", emails)
print("Phones:", phones)
print("Dates:", dates)
print("URLs:", urls)
print("Hashtags:", hashtags)

"""4.Corpus Loading and Corpus Statistics"""

import nltk
from nltk.corpus import brown

nltk.download("brown")

words = brown.words()
sentences = brown.sents()

print("Total words:", len(words))
print("Total sentences:", len(sentences))
print("Unique words:", len(set(words)))

average = len(words) / len(sentences)
print("Average sentence length:", average)

print("First 10 words:", words[:10])

"""WordNet — Synonyms, Antonyms, Hypernyms and Hyponyms"""

from nltk.corpus import wordnet as wn

word = "bank"

synsets = wn.synsets(word)

print("Synsets:")
for s in synsets:
    print(s.name())

print("\nSynonyms:")
for s in synsets:
    for lemma in s.lemmas():
        print(lemma.name())

print("\nAntonyms:")
for s in synsets:
    for lemma in s.lemmas():
        for ant in lemma.antonyms():
            print(ant.name())

print("\nHypernyms:")
print(synsets[0].hypernyms())

print("\nHyponyms:")
print(synsets[0].hyponyms())

"""# 6.Bag of words"""

from sklearn.feature_extraction.text import CountVectorizer

documents = ["cloud computing is useful", "cloud storage is useful"]

vectorizer = CountVectorizer()

matrix = vectorizer.fit_transform(documents)

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("BoW:")
print(matrix.toarray())

"""TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

documents = ["computer systems need security", "computer networks need security"]

vectorizer = TfidfVectorizer()

matrix = vectorizer.fit_transform(documents)

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("TF-IDF:")
print(matrix.toarray())

"""7.N-Gram Generation and Frequency Analysis"""

import nltk
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "Deep learning models recognize visual patterns."

words = word_tokenize(text)

unigram = list(ngrams(words, 1))
bigram = list(ngrams(words, 2))
trigram = list(ngrams(words, 3))

print("Unigrams:")
print(unigram)

print("Bigrams:")
print(bigram)

print("Trigrams:")
print(trigram)

"""8.Word Frequency Visualization"""

from nltk.tokenize import word_tokenize
from collections import Counter

text = "reading improves knowledge and reading develops knowledge"

words = word_tokenize(text.lower())

frequency = Counter(words)

print(frequency)
print(frequency.most_common())

"""BAR CHART"""

import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from collections import Counter

# Redefine text and frequency in this cell
text = "reading improves knowledge and reading develops knowledge"
words_tokenized = word_tokenize(text.lower())
frequency = Counter(words_tokenized)

words = list(frequency.keys())
counts = list(frequency.values())

plt.bar(words, counts)
plt.xlabel("Words")
plt.ylabel("Frequency")
plt.show()

"""9.Document and Sentence Similarity using Cosine Similarity"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

text1 = "Renewable energy reduces pollution."
text2 = "Solar energy reduces air pollution."

vectorizer = CountVectorizer()

matrix = vectorizer.fit_transform([text1, text2])

similarity = cosine_similarity(matrix)

print(similarity)
print("Similarity:", similarity[0][1])

"""10.POS Tagging"""

import nltk
from nltk.tokenize import word_tokenize

nltk.download("averaged_perceptron_tagger_eng")

text = "The talented scientist examined the reaction."

words = word_tokenize(text)

tags = nltk.pos_tag(words)

for word, tag in tags:
    print(word, "->", tag)

"""11.Noun Phrase and Multiword Expression Extraction"""

import nltk

text = "The experienced software engineer developed an application."

words = nltk.word_tokenize(text)
tags = nltk.pos_tag(words)

grammar = "NP: {<DT>?<JJ>*<NN.*>+}"

parser = nltk.RegexpParser(grammar)

tree = parser.parse(tags)

print(tree)
tree.pretty_print()

import nltk

text = "The data scientist studied artificial intelligence and machine learning."

expressions = ["data scientist", "artificial intelligence", "machine learning"]

for expression in expressions:
    if expression in text.lower():
        print(expression, "found")

import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("The young computer science student developed a new application.")

print("Noun phrases:")
for chunk in doc.noun_chunks:
    print(chunk.text)

text = "Machine learning and artificial intelligence are important."

phrases = ["machine learning", "artificial intelligence"]

for p in phrases:
    if p in text.lower():
        print(p)

"""12. Handling Unknown Words"""

import nltk

nltk.download("punkt_tab")
vocab = set(nltk.word_tokenize("python is a programming language"))

text = nltk.word_tokenize("python is a powerful tool")

result = [word if word in vocab else "<UNK>" for word in text]

print(result)

"""13. Shallow Parsing and Chunking"""

import nltk

nltk.download("averaged_perceptron_tagger_eng")

text = "The student reads a book in the library."

words = nltk.word_tokenize(text)
tags = nltk.pos_tag(words)

grammar = """
NP: {<DT>?<JJ>*<NN.*>+}
PP: {<IN><NP>}
VP: {<VB.*><NP|PP>*}
"""

parser = nltk.RegexpParser(grammar)

tree = parser.parse(tags)

tree.pretty_print()

"""14.dependency parsing"""

import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("The cat chased the mouse.")

for word in doc:
    print(word.text, "-> Head:", word.head.text, "Dependency:", word.dep_)

"""15. TreeBank Data Exploration"""

import nltk

nltk.download("treebank")

from nltk.corpus import treebank

sentence = treebank.tagged_sents()[0]

for word, tag in sentence:
    print(word, "->", tag)

"""16. Sentence Meaning Representation"""

sentences = {
    "Ravi is a student": "Student(Ravi)",
    "Ravi reads a book": "Reads(Ravi, Book)",
    "Anu likes music": "Likes(Anu, Music)",
}

for sentence, meaning in sentences.items():
    print(sentence)
    print("Logical form:", meaning)

"""17. Lexical Semantic Analysis Using WordNet Similarity"""

from nltk.corpus import wordnet as wn
import nltk

nltk.download("wordnet")
nltk.download("omw-1.4")

word1 = wn.synsets("dog")[0]
word2 = wn.synsets("cat")[0]

print("Similarity:", word1.path_similarity(word2))

"""18. Word Sense Disambiguation Using Lesk"""

from nltk.wsd import lesk
from nltk.tokenize import word_tokenize

sentence = "I went to the bank to deposit money."

words = word_tokenize(sentence)

sense = lesk(words, "bank")

print("Meaning:")
print(sense)
print(sense.definition())

"""19. WordNet-Based Meaning Disambiguation"""

from nltk.corpus import wordnet as wn
import nltk

nltk.download("wordnet")
nltk.download("omw-1.4")

word = "bank"

for syn in wn.synsets(word):
    print(syn.name())
    print(syn.definition())

"""20. Text Coherence Using Sentence Similarity"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sentences = [
    "Machine learning is used in healthcare.",
    "Machine learning helps doctors detect diseases.",
    "Doctors use medical data for diagnosis.",
]

vectorizer = TfidfVectorizer()

vectors = vectorizer.fit_transform(sentences)

for i in range(len(sentences) - 1):

    similarity = cosine_similarity(vectors[i], vectors[i + 1])

    print("Sentence", i + 1, "and Sentence", i + 2, "=", similarity[0][0])


import nltk

nltk.download("treebank")
from nltk.corpus import treebank

# Get the first parsed sentence from the Treebank corpus
# Each item in treebank.parsed_sents() is an nltk.tree.Tree object
parsed_sentence = treebank.parsed_sents()[0]

print("First parsed sentence from Treebank:")
# Pretty-print the parse tree
parsed_sentence.pretty_print()

print("\nTree in bracket notation:")
print(parsed_sentence)
